version: '3.8'

services:
  app:
    build:
      context: .
      target: builder  # Use the builder stage from Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Mount your code into the container
    working_dir: /app
    command: go run . # Run like you did with 'go run'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=mydatabase
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
